services:
  hackodisha:
    build:
      context: .
      dockerfile: Hackodisha/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-me}
    restart: unless-stopped
    depends_on:
      - mongodb

  moneygoals:
    image: node:18
    working_dir: /app
    volumes:
      - ./moneygoals:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/moneygoals}
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  ml_service:
    build:
      context: .
      dockerfile: ml_service/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongo-data:


